CREATE DATABASE flamengo_analytics;

CREATE TABLE IF NOT EXISTS partidas_flamengo (
    match_id INT PRIMARY KEY,
    campeonato VARCHAR(100),
    temporada VARCHAR(10),
    rodada VARCHAR(50),
    data_jogo TIMESTAMP,
    estadio VARCHAR(100),
    cidade VARCHAR(100),
    arbitro VARCHAR(100),
    mando VARCHAR(10),
    adversario VARCHAR(100),
    status VARCHAR(20),
    gols_flamengo INT,
    gols_adversario INT,
    gols_fla_intervalo INT,
    gols_adv_intervalo INT,
    resultado VARCHAR(10),
    formacao_flamengo VARCHAR(20),
    formacao_adversario VARCHAR(20),
    tecnico_flamengo VARCHAR(100),
    posse_bola_pct NUMERIC(5,2),
    chutes_gol INT,
    chutes_fora INT,
    chutes_totais INT,
    chutes_bloqueados INT,
    chutes_dentro_area INT,
    chutes_fora_area INT,
    faltas INT,
    escanteios INT,
    impedimentos INT,
    cartoes_amarelos INT,
    cartoes_vermelhos INT,
    defesas_goleiro INT,
    passes_totais INT,
    passes_certos INT,
    precisao_passe_pct NUMERIC(5,2),
    xg NUMERIC(5,2)
);